### ISSUE TITLE
Is LAGCN able to make use of target-related infomtion, like TL-HGBI?

### ISSUE THREAD

**Issue by e-yi** [storyandwine/LAGCN#1]
I'd like to compare my method with yours, but it feels kind of unfair since my model also uses target-related information (drug-target interactions, disease-target interactions, protein-protein interactions). It would be really helpful if you can show me how to use LAGCN to handle tri-layer network.

**Comment by storyandwine** [comment]
Thank you very much for noticing my research and opening the issue!
Considering more biological entities involved in the drug–disease associations, such as targets and so on, is our future work and the direction of effort. But unfortunately, for the time being, no suitable way has been found. 
Best wishes!

**Comment by e-yi** [comment]
OK. Thanks for your quick reply. Looking forward to see more of your work in the future! 😀
