### ISSUE TITLE
About the Similarity Matrix

### ISSUE THREAD

**Issue by youngbo9i** [storyandwine/LAGCN#10]
Your drug similarity matrix does not match the Jaccard similarity matrix properties, for example, the diagonal elements should all be 1 but you have them all at 0. Am I missing something? Thank you in advance.

**Comment by storyandwine** [comment]
Because GCN's normalization has one step of adding identity matrix, there is no need to set diagonal elements as 1 in similarity matrix.

**Comment by youngbo9i** [comment]
> identity matrix

Isn't the identity matrix added to the adjacency matrix, which is equivalent to self-connection, but the diagonal of the similarity matrix is still 0, am I missing something? Thank you in advance.

**Comment by storyandwine** [comment]
![image](https://user-images.githubusercontent.com/27343352/155836375-f66819e5-4792-4539-b8ca-73c25727ad59.png)

**Comment by youngbo9i** [comment]
> ![image](https://user-images.githubusercontent.com/27343352/155836375-f66819e5-4792-4539-b8ca-73c25727ad59.png)

Understood, thank you very much for your patience
