### ISSUE TITLE
About datasets

### ISSUE THREAD

**Issue by youngbo9i** [storyandwine/LAGCN#11]
Hi, your repository gives drug similarity based on the Jaccard algorithm and disease-disease similarity based on MeSH is it? Thank you in advance

**Comment by storyandwine** [comment]
Yes

**Comment by youngbo9i** [comment]
> 是的

The drug similarity given is for the target only feature is it? Thanks

**Comment by storyandwine** [comment]
> > 是的
> 
> The drug similarity given is for the target only feature is it? Thanks

Yes
