### ISSUE TITLE
request the target feature of drug and mesh of disease 

### ISSUE THREAD

**Issue by abbasi72** [storyandwine/LAGCN#13]
hello, 
I need to drug target feature and the MESH of disease ( the raw data that drug similarity and disease similarity are extracted from these )
thank you for giving it to me ..

**Comment by storyandwine** [comment]
> [raw_data.zip](https://github.com/storyandwine/LAGCN/files/6341687/raw_data.zip) Here is the source data that has not been processed. Best Wishes！
