### ISSUE TITLE
在构造异构网络时好像没有如论文中所言对相似性矩阵进行标准化

### ISSUE THREAD

**Issue by porvinci** [storyandwine/LAGCN#14]
在`main.py`文件中的第16行
```
adj = constructHNet(train_drug_dis_matrix, drug_matrix, dis_matrix)
```
`utils.py`文件中
```
def constructHNet(drug_dis_matrix, drug_matrix, dis_matrix):
    mat1 = np.hstack((drug_matrix, drug_dis_matrix))
    mat2 = np.hstack((drug_dis_matrix.T, dis_matrix))
    return np.vstack((mat1, mat2))
```
此处构造了异构网络，后续将作为input graph G，但是好像并没有如论文中所言（论文中的构造异构网络部分）对相似性矩阵进行归一化操作？

**Comment by storyandwine** [comment]
It has been processed in advance. For more normalization details, please see https://github.com/xiangyue9607/SCMFDD/blob/master/Experiment_SCMFDD_All.m#L224

**Comment by porvinci** [comment]
好的，多谢
