### ISSUE TITLE
程序运行问题

### ISSUE THREAD

**Issue by night-changes** [storyandwine/LAGCN#17]
您好！
我按照说明运行了main.py 文件 ，但运行结束没有得到任何结果性的文件如 一个新的drug-dis矩阵，无法判断预测的具体情况！

**Comment by storyandwine** [comment]
Well, the new predicted drug-dis matrix can be found in https://github.com/storyandwine/LAGCN/blob/a490d4917090339f47af4f460ed0c2138b837a6a/code/main.py#L92 named predict_y_proba. 
This is an array in numpy format, you can use np.savetxt() or other functions to save as a file.

**Comment by night-changes** [comment]
> Well, the new predicted drug-dis matrix can be found in
> 
> https://github.com/storyandwine/LAGCN/blob/a490d4917090339f47af4f460ed0c2138b837a6a/code/main.py#L92
> 
> named predict_y_proba.
> This is an array in numpy format, you can use np.savetxt() or other functions to save as a file.

谢谢 我已解决！
