### ISSUE TITLE
数据和代码问题

### ISSUE THREAD

**Issue by SunRuir** [storyandwine/LAGCN#18]
您好！
请问您在基础数据集上与其它六种方法比较的程序是发表在哪利呀，或者是从哪里找到的呀

**Comment by storyandwine** [comment]
You can follow the thread of the citations back to the papers on these contrasting methods to find or build their respective code implementations.  And then simply replace the Predict Score function in LAGCN to do a fair comparison between the different methods.  Some methods may not be written in python, which requires you to use import and export functions flexibly to exchange data through the intermediary of text files.

**Comment by SunRuir** [comment]
好的！非常感谢您的回复
