### ISSUE TITLE
project 

### ISSUE THREAD

**Issue by mahmoudi-wael10** [storyandwine/LAGCN#2]
hi 
Can you give me a source for data and The result obtained in this program  For comparison with my result please
mwael412@gmail.com my email
cordially.

**Comment by storyandwine** [comment]
Hi,
Source data that has not been processed has been packaged and sent to your mailbox.
Best Wishes！

**Comment by storyandwine** [comment]
[raw_data.zip](https://github.com/storyandwine/LAGCN/files/6341687/raw_data.zip)
Here is the source data that has not been processed.
Best Wishes！

**Comment by mahmoudi-wael10** [comment]
Hello
Can you give me an arcticle who ken help me to undertsnad more for your
code
and  explain more the method used in your algorithm
Cordialy

**Comment by storyandwine** [comment]
Hi!
Here is the full essay link：
https://doi.org/10.1093/bib/bbaa243

**Comment by mahmoudi-wael10** [comment]
Hello,
I am a research master student working on a project  end of study
Project name : drug-disease association
I want to modify the body of the algorithm. In order to get a better
result, can you help me to change method   LAGCN to an other method please
I'm under time pressure
and I want to help me
cordialy

**Comment by storyandwine** [comment]
Hi,
To change other methods, you just need to re-write  the PredictScore function in main.py, where input is drug_disease_matrix and extra informations, output will be predicted drug_disease_scores in same shape with drug_disease_matrix.
After changing PredictScore function, it will be easier to compare with orther methods.
Best regards!
