### ISSUE TITLE
Drug and Disease Names

### ISSUE THREAD

**Issue by youngbo9i** [storyandwine/LAGCN#8]
Hello, do you have the names of the drugs and diseases corresponding to this dataset? thanks.

**Comment by storyandwine** [comment]
https://github.com/storyandwine/LAGCN/issues/4#issuecomment-877658397 #4

**Comment by youngbo9i** [comment]
Thanks a lot

> [#4（评论）](https://github.com/storyandwine/LAGCN/issues/4#issuecomment-877658397) #4

Thanks a lot

**Comment by youngbo9i** [comment]
> [#4（评论）](https://github.com/storyandwine/LAGCN/issues/4#issuecomment-877658397) #4

Thanks a lot
