### ISSUE TITLE
About datasets

### ISSUE THREAD

**Issue by youngbo9i** [storyandwine/LAGCN#9]
Hello, I see that the Therapeutic dataset is also used in your work, but it is not provided in the project. Is it convenient to provide it, thank you!

**Comment by storyandwine** [comment]
[interaction_matrix.txt](https://github.com/storyandwine/LAGCN/files/7877180/interaction_matrix.txt)
Where 1 for Therapeutic.

**Comment by youngbo9i** [comment]
> 

 Thank you very much！

**Comment by shahinghasemi** [comment]
Hello @storyandwine, Would you please explain about this data? It consists of {0, 1, -1} what do they mean? what's the relationship between this dataset and the main dataset? are they disjoints?

**Comment by storyandwine** [comment]
> 

0 for non-associations, 1 for therapeutic, for details see http://ctdbase.org/toolTip.ajx?type=actiontype&ixnType=CHEMICAL-DISEASE&code=t , -1 for harmful, for details see http://ctdbase.org/toolTip.ajx?type=actiontype&ixnType=CHEMICAL-DISEASE&code=m

**Comment by storyandwine** [comment]
> 

Main dataset 1 = {1,-1} 0 = {0}
Therapeutic dataset 1= {1}, 0 = {0,-1} @[shahinghasemi](https://github.com/shahinghasemi)

**Comment by shahinghasemi** [comment]
@storyandwine thanks you for your clarification. How did you split this therapeutic data in your work? I guess for interactions (1s) you probably split them into 5 sets, but I am not sure for 0s. Did you use all the 0s in both training and testing? or just like ones, the zeros are split into 5 sets and 4 of them are used in training and one of them in testing?

**Comment by storyandwine** [comment]
> @storyandwine thanks you for your clarification. How did you split this therapeutic data in your work? I guess for interactions (1s) you probably split them into 5 sets, but I am not sure for 0s. Did you use all the 0s in both training and testing? or just like ones, the zeros are split into 5 sets and 4 of them are used in training and one of them in testing?

It's same to issue #5.
